/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package staff_management_system.UI;

import Helpers.MessageDialogHelper;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import staff_management_system.BUS.CongViecBUS;
import staff_management_system.DTO.CongViec;

/**
 *
 * @author Chi Thien
 */
public class CongViecUI extends javax.swing.JFrame {
    DefaultTableModel model;
    public static ArrayList<CongViec> listCongViec;
    /**
     * Creates new form CongViecUI
     */
    public CongViecUI() {
        initComponents();
        readData();
        loadData(listCongViec);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void readData() {
        CongViecBUS bus = new CongViecBUS();
        try {
            listCongViec = bus.getCongViecs();
        } catch (Exception ex) {
            Logger.getLogger(CongViecUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void loadData(ArrayList<CongViec> list) {
        Vector header = new Vector();
        header.add("Mã công việc");
        header.add("Tên công việc");
        model = new DefaultTableModel(header, 0);

        String[] data = new String[header.size()];

        for (int i = 0; i < list.size(); i++) {
            data[0] = list.get(i).getMaCongViec();
            data[1] = list.get(i).getTenCongViec();
            model.addRow(data);
        }

        tblCongViec.setModel(model);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaCongViec = new javax.swing.JTextField();
        txtTenCongViec = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCongViec = new javax.swing.JTable();
        btLuu = new javax.swing.JButton();
        btCapNhat = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btLamMoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("CÔNG VIỆC");

        jLabel2.setText("Mã công việc:");

        jLabel3.setText("Tên công việc:");

        tblCongViec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã công việc", "Tên công việc"
            }
        ));
        tblCongViec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCongViecMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCongViec);

        btLuu.setText("Thêm");
        btLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuActionPerformed(evt);
            }
        });

        btCapNhat.setText("Cập nhật");
        btCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhatActionPerformed(evt);
            }
        });

        btDelete.setText("Xóa");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        btLamMoi.setText("Làm mới");
        btLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(btLuu)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtMaCongViec)
                                        .addComponent(txtTenCongViec, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btCapNhat)
                                        .addGap(44, 44, 44)
                                        .addComponent(btDelete)
                                        .addGap(44, 44, 44)
                                        .addComponent(btLamMoi)))))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaCongViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenCongViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLuu)
                    .addComponent(btCapNhat)
                    .addComponent(btDelete)
                    .addComponent(btLamMoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhatActionPerformed
        // TODO add your handling code here:
        CongViec congViec = new CongViec();
        congViec.setMaCongViec(txtMaCongViec.getText());
        congViec.setTenCongViec(txtTenCongViec.getText());

        int i = MessageDialogHelper.showConFirmDialog(jLabel1, "Đồng ý cập nhật?", "Xác nhận");
        if (i == JOptionPane.NO_OPTION) {
            return;
        }

        CongViecBUS bus = new CongViecBUS();
        if (bus.updateCongViec(congViec)) {
            MessageDialogHelper.showMessageDialog(jLabel1, "Cập nhật thông tin công việc thành công!", "Thông báo");
            readData();
            loadData(listCongViec);
            btLamMoiActionPerformed(evt);
        } else
            MessageDialogHelper.showErrorDialog(jLabel1, "Cập thông thông tin công việc thất bại", "Lỗi");
    }//GEN-LAST:event_btCapNhatActionPerformed

    private void btLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuActionPerformed
        // TODO add your handling code here:
        try {
            CongViec congViec = new CongViec();
            congViec.setMaCongViec(txtMaCongViec.getText());
            congViec.setTenCongViec(txtTenCongViec.getText());

            CongViecBUS bus = new CongViecBUS();
            bus.addCongViec(congViec);
            readData();
            loadData(listCongViec);
            btLamMoiActionPerformed(evt);

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(jLabel1, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btLuuActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        int i = tblCongViec.getSelectedRow();

        int opt = MessageDialogHelper.showConFirmDialog(jLabel1, "Đồng ý xóa thông tin công việc?", "Xác nhận");
        if (opt == JOptionPane.NO_OPTION) {
            return;
        }
        
        CongViecBUS bus = new CongViecBUS();
        if (bus.delCongViec(listCongViec.get(i).getMaCongViec())) {
            listCongViec.remove(i);
            MessageDialogHelper.showMessageDialog(jLabel1, "Xóa thông tin công việc thành công!", "Thông báo");
            readData();
            loadData(listCongViec);
            btLamMoiActionPerformed(evt);
        } else {
            MessageDialogHelper.showErrorDialog(jLabel1, "Xóa thông tin công việc không thành công", "Lỗi");
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLamMoiActionPerformed
        // TODO add your handling code here:
        txtMaCongViec.setText("");
        txtTenCongViec.setText("");
    }//GEN-LAST:event_btLamMoiActionPerformed

    private void tblCongViecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCongViecMouseClicked
        // TODO add your handling code here:
        int i = tblCongViec.getSelectedRow();
        txtMaCongViec.setText(listCongViec.get(i).getMaCongViec());
        txtTenCongViec.setText(listCongViec.get(i).getTenCongViec());
    }//GEN-LAST:event_tblCongViecMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CongViecUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CongViecUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CongViecUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CongViecUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CongViecUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCapNhat;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btLamMoi;
    private javax.swing.JButton btLuu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblCongViec;
    private javax.swing.JTextField txtMaCongViec;
    private javax.swing.JTextField txtTenCongViec;
    // End of variables declaration//GEN-END:variables
}
