/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package staff_management_system.UI;

import Helpers.MessageDialogHelper;
import java.text.DateFormat;
import java.text.ParseException;
//import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import staff_management_system.BUS.PhongBanBUS;
import staff_management_system.DTO.PhongBan;
/**
 *
 * @author Chi Thien
 */
public class PhongBanUI extends javax.swing.JFrame {
    DefaultTableModel model;
    public static ArrayList<PhongBan> listPhongBan;
    /**
     * Creates new form PhongBan
     */
    public PhongBanUI() {
        initComponents();
        readData();
        loadData(listPhongBan);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaPhongBan = new javax.swing.JTextField();
        txtTenPhongBan = new javax.swing.JTextField();
        txtMaCongViec = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        btThem = new javax.swing.JButton();
        btLuu = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhongBan = new javax.swing.JTable();
        btLamMoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("PHÒNG BAN");

        jLabel2.setText("Mã phòng ban:");

        jLabel3.setText("Tên phòng ban:");

        jLabel4.setText("Mã công việc:");

        jLabel5.setText("Địa chỉ:");

        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btLuu.setText("Câp nhật");
        btLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuActionPerformed(evt);
            }
        });

        btDelete.setText("Xóa");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        tblPhongBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã phòng ban", "Tên phòng ban", "Mã công việc", "Địa chỉ"
            }
        ));
        tblPhongBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhongBanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhongBan);

        btLamMoi.setText("Làm mới");
        btLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(284, 284, 284))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaPhongBan)
                            .addComponent(txtTenPhongBan)
                            .addComponent(txtMaCongViec)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(btLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btThem)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLuu))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMaCongViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btDelete)
                        .addGap(32, 32, 32)
                        .addComponent(btLamMoi)))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        int i = tblPhongBan.getSelectedRow();
        int opt = MessageDialogHelper.showConFirmDialog(jLabel1, "Đồng ý xóa thông tin phòng ban?", "Xác nhận");
        if (opt == JOptionPane.NO_OPTION) {
            return;
        }
        
        PhongBanBUS bus = new PhongBanBUS();
        if (bus.delPhongBan(listPhongBan.get(i).getMaPhongBan())) {
            listPhongBan.remove(i);
            MessageDialogHelper.showMessageDialog(jLabel1, "Xóa thông tin phòng ban thành công!", "Thông báo");
            readData();
            loadData(listPhongBan);
            btLamMoiActionPerformed(evt);
        } else {
            MessageDialogHelper.showErrorDialog(jLabel1, "Xóa thông tin phòng ban không thành công", "Lỗi");
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLamMoiActionPerformed
        // TODO add your handling code here:
        txtMaPhongBan.setText("");
        txtTenPhongBan.setText("");
        txtMaCongViec.setText("");
        txtDiaChi.setText("");
    }//GEN-LAST:event_btLamMoiActionPerformed

    private void btLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuActionPerformed
        // TODO add your handling code here:
            PhongBan phongBan = new PhongBan();
            phongBan.setMaPhongBan(txtMaPhongBan.getText());
            phongBan.setTenPhongBan(txtTenPhongBan.getText());
            phongBan.setMaCongViec(txtMaCongViec.getText());
            phongBan.setDiaChi(txtDiaChi.getText());
            
        int i = MessageDialogHelper.showConFirmDialog(jLabel1, "Đồng ý cập nhật?", "Xác nhận");
        if (i == JOptionPane.NO_OPTION) {
            return;
        }

        PhongBanBUS bus = new PhongBanBUS();
        if (bus.updatePhongBan(phongBan)) {
            MessageDialogHelper.showMessageDialog(jLabel1, "Cập nhật thông tin phòng ban thành công!", "Thông báo");
            readData();
            loadData(listPhongBan);
            btLamMoiActionPerformed(evt);
        } else
            MessageDialogHelper.showErrorDialog(jLabel1, "Cập thông thông tin thất bại", "Lỗi");
    }//GEN-LAST:event_btLuuActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        try {
            PhongBan phongBan = new PhongBan();
            phongBan.setMaPhongBan(txtMaPhongBan.getText());
            phongBan.setTenPhongBan(txtTenPhongBan.getText());
            phongBan.setMaCongViec(txtMaCongViec.getText());
            phongBan.setDiaChi(txtDiaChi.getText());

            PhongBanBUS bus = new PhongBanBUS();
            bus.addPhongBan(phongBan);
            readData();
            loadData(listPhongBan);
            btLamMoiActionPerformed(evt);

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(jLabel1, e.getMessage(), "Lỗi");
        }
        
    }//GEN-LAST:event_btThemActionPerformed

    private void tblPhongBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhongBanMouseClicked
        // TODO add your handling code here:
        int i = tblPhongBan.getSelectedRow();
        txtMaPhongBan.setText(listPhongBan.get(i).getMaPhongBan());
        txtTenPhongBan.setText(listPhongBan.get(i).getTenPhongBan());
        txtMaCongViec.setText(listPhongBan.get(i).getMaCongViec());
        txtDiaChi.setText(listPhongBan.get(i).getDiaChi());
    }//GEN-LAST:event_tblPhongBanMouseClicked

    /**
     * @param args the command line arguments
     */
    public void readData() {
        PhongBanBUS bus = new PhongBanBUS();
        try {
            listPhongBan = bus.getPhongBans();
        } catch (Exception ex) {
            Logger.getLogger(PhongBanUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void loadData(ArrayList<PhongBan> list) {
        Vector header = new Vector();
        header.add("Mã phòng ban");
        header.add("Tên phòng ban");
        header.add("Mã công việc");
        header.add("Địa chỉ");
        model = new DefaultTableModel(header, 0);

        String[] data = new String[header.size()];

        for (int i = 0; i < list.size(); i++) {
            data[0] = list.get(i).getMaPhongBan();
            data[1] = list.get(i).getTenPhongBan();
            data[2] = list.get(i).getMaCongViec();
            data[3] = list.get(i).getDiaChi();
            model.addRow(data);
        }

        tblPhongBan.setModel(model);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhongBanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhongBanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhongBanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhongBanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhongBanUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btLamMoi;
    private javax.swing.JButton btLuu;
    private javax.swing.JButton btThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblPhongBan;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaCongViec;
    private javax.swing.JTextField txtMaPhongBan;
    private javax.swing.JTextField txtTenPhongBan;
    // End of variables declaration//GEN-END:variables
}
