/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package staff_management_system.UI.MainContentPanels;

import Helpers.MessageDialogHelper;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import staff_management_system.BUS.BangChamCongBUS;
import static staff_management_system.BUS.BangChamCongBUS.dscc;
import staff_management_system.BUS.NhanVienBUS;
import static staff_management_system.BUS.NhanVienBUS.dsnv;
import staff_management_system.DTO.BangChamCong;
import staff_management_system.DTO.NhanVien;

/**
 *
 * @author Utech
 */
public class BangChamCongGUI extends javax.swing.JPanel {
    BangChamCongBUS bus = new BangChamCongBUS();
    DefaultTableModel model;
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd"); 
    int count = 0;

    /**
     * Creates new form BangChamCongGUI
     */
    public BangChamCongGUI() {
        initComponents();
        cbTrangThai.setSelectedItem(null);
        readData();
        
        for(BangChamCong cc : dscc)
            count++;
        
        NhanVienBUS nvbus = new NhanVienBUS();
        nvbus.getNhanViens();
        for(NhanVien nv : dsnv)
            cbMaNV.addItem(nv.getMaNV());
            
        loadData(dscc);
    }
    
    public void readData() {
        BangChamCongBUS bus = new BangChamCongBUS();
        try {
            bus.getBangChamCongs();
        } catch (Exception ex) {
            Logger.getLogger(BangChamCongUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void loadData(ArrayList<BangChamCong> list) {
        Vector header = new Vector();
        header.add("Mã nhân viên");
        header.add("Ngày");
        header.add("Trạng thái");
        model = new DefaultTableModel(header, 0);

        String[] data = new String[header.size()];

        for (int i = 0; i < list.size(); i++) {
            data[0] = list.get(i).getMaNV();
            data[1] = formatter.format(list.get(i).getDate());
            data[2] = list.get(i).getTrangThai();
            model.addRow(data);
        }

        tblChamCong.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txMaNV = new javax.swing.JTextField();
        dateChooser = new com.toedter.calendar.JDateChooser();
        cbTrangThai = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btLuu = new javax.swing.JButton();
        btLammoi = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btCapNhat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChamCong = new javax.swing.JTable();
        cbMaNV = new javax.swing.JComboBox<>();

        txMaNV.setBorder(javax.swing.BorderFactory.createTitledBorder("Mã nhân viên"));

        dateChooser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ngày tháng năm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        cbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Có đi làm", "Vắng có phép", "Vắng không phép" }));
        cbTrangThai.setBorder(javax.swing.BorderFactory.createTitledBorder("Trạng thái"));

        btLuu.setText("Thêm");
        btLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuActionPerformed(evt);
            }
        });

        btLammoi.setText("Làm mới");
        btLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLammoiActionPerformed(evt);
            }
        });

        btDelete.setText("Xóa");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        btCapNhat.setText("Cập nhật");
        btCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(btLammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btCapNhat)
                .addGap(30, 30, 30)
                .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDelete)
                    .addComponent(btLammoi)
                    .addComponent(btLuu)
                    .addComponent(btCapNhat))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        tblChamCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblChamCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChamCongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChamCong);

        cbMaNV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mã nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbMaNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(271, 271, 271))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(cbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuActionPerformed
        Calendar c = Calendar.getInstance();
        c.setTime(dateChooser.getDate());

        try {
            for (int i = 0; i < 30; i++) {
                BangChamCong chamCong = new BangChamCong();
                chamCong.setMaNV( "" + (cbMaNV.getSelectedItem()));

                c.add(Calendar.DAY_OF_MONTH, 1);
                Date dateAfter = c.getTime();

                chamCong.setDate(dateAfter);
                chamCong.setTrangThai(String.valueOf(cbTrangThai.getSelectedItem()));

                BangChamCongBUS bus = new BangChamCongBUS();
                bus.addChamCong(chamCong);
                readData();
                loadData(dscc);
                
            }

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(this.jPanel3, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btLuuActionPerformed

    private void btLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLammoiActionPerformed
        txMaNV.setText("");
        dateChooser.setDate(null);
        cbTrangThai.setSelectedItem(null);
    }//GEN-LAST:event_btLammoiActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        int i = tblChamCong.getSelectedRow();

        int opt = MessageDialogHelper.showConFirmDialog(jScrollPane1, "Đồng ý xóa thông tin chấm công?", "Xác nhận");
        if (opt == JOptionPane.NO_OPTION) {
            return;
        }

        BangChamCongBUS bus = new BangChamCongBUS();
        if (bus.delChamCong(dscc.get(i))) {
            dscc.remove(i);
            MessageDialogHelper.showMessageDialog(jScrollPane1, "Xóa thông tin chấm công thành công!", "Thông báo");
            readData();
            loadData(dscc);
            btLammoiActionPerformed(evt);
        } else {
            MessageDialogHelper.showErrorDialog(jScrollPane1, "Xóa thông tin chấm công không thành công", "Lỗi");
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhatActionPerformed
        BangChamCong chamCong = new BangChamCong();
        chamCong.setMaNV(txMaNV.getText());
        chamCong.setDate(dateChooser.getDate());
        chamCong.setTrangThai(String.valueOf(cbTrangThai.getSelectedItem()));

        int i = MessageDialogHelper.showConFirmDialog(jScrollPane1, "Đồng ý cập nhật?", "Xác nhận");
        if (i == JOptionPane.NO_OPTION) {
            return;
        }

        BangChamCongBUS bus = new BangChamCongBUS();
        if (bus.updateChamCong(chamCong)) {
            MessageDialogHelper.showMessageDialog(jScrollPane1, "Cập nhật thông tin chấm công thành công!", "Thông báo");
            readData();
            loadData(dscc);
            btLammoiActionPerformed(evt);
        } else
        MessageDialogHelper.showErrorDialog(jScrollPane1, "Cập thông thông tin chấm công thất bại", "Lỗi");
    }//GEN-LAST:event_btCapNhatActionPerformed

    private void tblChamCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChamCongMouseClicked
        int i = tblChamCong.getSelectedRow();
        txMaNV.setText(dscc.get(i).getMaNV());
        dateChooser.setDate(dscc.get(i).getDate());
        cbTrangThai.setSelectedItem(dscc.get(i).getTrangThai());
    }//GEN-LAST:event_tblChamCongMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCapNhat;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btLammoi;
    private javax.swing.JButton btLuu;
    private javax.swing.JComboBox<String> cbMaNV;
    private javax.swing.JComboBox<String> cbTrangThai;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblChamCong;
    private javax.swing.JTextField txMaNV;
    // End of variables declaration//GEN-END:variables
}
